# Generated by Django 3.1.5 on 2021-02-01 19:46

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('content', tinymce.models.HTMLField()),
                ('who', models.CharField(max_length=100)),
                ('what', models.CharField(max_length=100)),
                ('why', models.CharField(max_length=100)),
                ('priority', models.CharField(max_length=100)),
                ('time_bound', models.CharField(max_length=100)),
                ('story', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sw_app.story')),
            ],
        ),
    ]
