# Generated by Django 3.1.5 on 2021-02-13 10:42

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Epic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('overview', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('story_type', models.CharField(max_length=100)),
                ('epic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sw_app.epic')),
            ],
        ),
        migrations.CreateModel(
            name='Small',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField()),
                ('story', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sw_app.story')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.TextField()),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sw_app.story')),
            ],
        ),
        migrations.CreateModel(
            name='Related',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sw_app.story')),
            ],
        ),
        migrations.CreateModel(
            name='Independent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField()),
                ('story', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sw_app.story')),
            ],
        ),
        migrations.CreateModel(
            name='DetailedAppropriately',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', django_quill.fields.QuillField(help_text='Bir ürün iş listesinde üstte olan kullanıcı hikayeleri ilk geliştirilecek hikayelerdir. Bu yüzden bu hikayeler, ekibin anlayabilmesi ve büyüklüğünü ölçümleyebilmesi için yeteri kadar detaylandırılmalıdır. Yeteri kadar dememin bir sebebi var. Her şeyin en ince detayına kadar açıklanması değil de geliştirici ekibin ölçümleyebilmesi ve planlayabilmesine imkan sağlayacak kadar detaylandırılmış olması yeterlidir.')),
                ('end_point', models.TextField()),
                ('story_input', models.TextField()),
                ('story_output', django_quill.fields.QuillField()),
                ('data_source', django_quill.fields.QuillField()),
                ('formula', models.TextField()),
                ('internal_apis', models.TextField()),
                ('external_apis', models.TextField()),
                ('authantication', models.TextField()),
                ('max_response_time', models.TextField()),
                ('story', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sw_app.story')),
            ],
        ),
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=100)),
                ('approver', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('note', models.CharField(max_length=100)),
                ('story', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sw_app.story')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('who', models.TextField(help_text='As a .....')),
                ('what', models.TextField(help_text='I want .....')),
                ('why', models.TextField(help_text='So that .....')),
                ('priority', models.IntegerField(help_text='0 is most important 100 is least important')),
                ('time_bound', models.DateField()),
                ('story', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sw_app.story')),
            ],
        ),
        migrations.CreateModel(
            name='AcceptanceCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.CharField(max_length=100)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sw_app.story')),
            ],
        ),
    ]
